### ISSUE TITLE
Compile failures

### ISSUE THREAD

**Issue by hvr** [Chrisr850/Villefort#1]
First off, welcome to Hackage!

Your package caught my attention because it was flagged by Hackage's experimental CI system, specifically it failed with

```
Configuring component lib from Villefort-0.1.0.2...
Preprocessing library Villefort-0.1.0.2...

src/Database.hs:4:8:
    Could not find module ‘Control.Monad.IO.Class’
    It is a member of the hidden package ‘transformers-0.5.4.0@CBZP4azR07y8fwUbBRPPsd’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.2.0@trans_GZTjP9K5WFq01xC9BAGQpF’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Failed to build Villefort-0.1.0.2 (which is required by exe:Villefort
from Villefort-0.1.0.2).
```

This is because `Control.Monad.IO.Class` became part of `base` only starting with `base-4.9`; however your `.cabal` file claims compatibility with `base >= 4.7 && < 5` which is provably false.

Please be aware that accurate version bounds are also mandated by the [PVP](http://pvp.haskell.org/), and packages are expected to follow the PVP as part of the Hackage guidelines (see http://hackage.haskell.org/upload).  The motivation for this guideline is that otherwise it can have various knock off consequences, such as Hackage possibly not being able to generate Haddock documentation for your package, install-plans degrading over time, as well generally resulting in a poor experience for users since they'll risk running into the compilation errors caused by inaccurate version bounds, and finally causing more work for us Hackage Trustees curating Hackage.

The `cabal gen-bounds` command can be used to help infer an initial set of version bounds, see  [Cabal User Guide | Generating dependency version bounds](http://cabal.readthedocs.io/en/latest/developing-packages.html#generating-dependency-version-bounds) for more details. Or if you use Stack, just add `pvp-bounds: both` to your `stack.yaml` file (see https://docs.haskellstack.org/en/stable/yaml_configuration/#pvp-bounds).

If you have any questions, feel free to ask me!

**Comment by Chrisr850** [comment]
Thanks for the heads up, I change the bounds for the base package as well as added bounds for the other packages that are being used.
